version: "3.9"
   
services:
  openvidu:
    image: openvidu/openvidu-dev
    environment:
      - SERVER_PORT=4443
      - DOMAIN_OR_PUBLIC_IP=127.0.0.1
      - OPENVIDU_SECRET=openvidu
      - CERTIFICATE_TYPE=selfsigned
      - LETSENCRYPT_EMAIL=
      - OPENVIDU_RECORDING=false

  nginx:
    image: nginx:1.20.2
    ports:
      - "4443:8043"
      - "3478:8078"
      - "5442:8042"
    volumes:
      - ./nginx/entrypoint.sh:/nginx/entrypoint.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    entrypoint: ["/nginx/entrypoint.sh"]

  openviducall:
    image: openvidu/openvidu-call:2.24.0
    restart: on-failure
    environment:    
      - SERVER_PORT=5442
      - OPENVIDU_URL=http://openvidu:4443
      - OPENVIDU_SECRET=openvidu
      - CALL_OPENVIDU_CERTTYPE=selfsigned
      - CALL_PRIVATE_ACCESS=false
      - CALL_USER=OPENVIDUAPP
      - CALL_SECRET=openvidu
      - CALL_ADMIN_SECRET=openvidu
      - CALL_RECORDING=false
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
